### ISSUE TITLE
Fix issues from Sprint 1

### ISSUE THREAD

**Issue by nateng98** [rainclouded/Concierge#152]
- [ ] ~~Change sessions to accounts in nginx.conf in docker-compose folder. _(Session service is deleted so having location /sessions/ here will cause nginx to crash)_~~
- [x] #173
- [x] #175
- [x] #192
- [x] #193

**Comment by rainclouded** [comment]
First issue I believe has already been fixed. Last two see #177.

**Comment by rainclouded** [comment]
All bugs fixed.
